// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MsEShop.Services.CouponAPI.Data;

#nullable disable

namespace MsEShop.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218122648_SeedCouponTable")]
    partial class SeedCouponTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MsEShop.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("double");

                    b.Property<DateTime>("LastUpdatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "10OFF",
                            CreatedOn = new DateTime(2026, 2, 18, 13, 26, 48, 323, DateTimeKind.Local).AddTicks(553),
                            DiscountAmount = 10.0,
                            LastUpdatedOn = new DateTime(2026, 2, 18, 13, 26, 48, 323, DateTimeKind.Local).AddTicks(614),
                            MinAmount = 20
                        },
                        new
                        {
                            Id = 2,
                            Code = "20OFF",
                            CreatedOn = new DateTime(2026, 2, 18, 13, 26, 48, 323, DateTimeKind.Local).AddTicks(643),
                            DiscountAmount = 20.0,
                            LastUpdatedOn = new DateTime(2026, 2, 18, 13, 26, 48, 323, DateTimeKind.Local).AddTicks(644),
                            MinAmount = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
